//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomado_MVC_UASD_Estudiante_ImageUpload.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstudianteDBEntities : DbContext
    {
        public EstudianteDBEntities()
            : base("name=EstudianteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEstudiante> tblEstudiantes { get; set; }
        public int EstudianteId { get; internal set; }
        public string Nombres { get; internal set; }
        public string Apellidos { get; internal set; }
        public string Direccion { get; internal set; }
        public string Telefono { get; internal set; }
        public int Cedula { get; internal set; }
        public string ImageUrl { get; internal set; }

        public static implicit operator tblEstudiante(EstudianteDBEntities v)
        {
            throw new NotImplementedException();
        }
    }
}
